### ISSUE TITLE
NoMethodError - undefined method `queue' for nil:NilClass:

### ISSUE THREAD

**Issue by micah** [chkelly/gitlab-irc#7]
I just tried to set this up, but when I test the web hook, I am told the following in the error log:

```
NoMethodError - undefined method `queue' for nil:NilClass:
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/irc.rb:286:in `send'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/user.rb:252:in `whois'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/user.rb:216:in `block in initialize'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/syncable.rb:65:in `call'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/syncable.rb:65:in `attr'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/user.rb:234:in `attr'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/user.rb:47:in `user'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/user.rb:342:in `block in mask'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/user.rb:337:in `gsub'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/user.rb:337:in `mask'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/target.rb:38:in `block in msg'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/target.rb:36:in `each'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/target.rb:36:in `msg'
        /var/lib/gems/1.9.1/gems/cinch-2.1.0/lib/cinch/channel.rb:398:in `msg'
        /home/micah/gitlab/gitlab-irc/lib/gitlab-irc.rb:33:in `block in say'
        /home/micah/gitlab/gitlab-irc/lib/gitlab-irc.rb:32:in `each'
        /home/micah/gitlab/gitlab-irc/lib/gitlab-irc.rb:32:in `say'
        /home/micah/gitlab/gitlab-irc/lib/gitlab-irc.rb:41:in `block (2 levels) in <top (required)>'
        /home/micah/gitlab/gitlab-irc/lib/gitlab-irc.rb:39:in `each'
        /home/micah/gitlab/gitlab-irc/lib/gitlab-irc.rb:39:in `block in <top (required)>'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1212:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1212:in `block in compile!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:785:in `[]'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:785:in `block (3 levels) in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:801:in `route_eval'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:785:in `block (2 levels) in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:822:in `block in process_route'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:820:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:820:in `process_route'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:784:in `block in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:783:in `each'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:783:in `route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:886:in `dispatch!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:719:in `block in call!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:871:in `block in invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:871:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:871:in `invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:719:in `call!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:705:in `call'
        /usr/lib/ruby/vendor_ruby/rack/protection/xss_header.rb:22:in `call'
        /usr/lib/ruby/vendor_ruby/rack/protection/path_traversal.rb:16:in `call'
        /usr/lib/ruby/vendor_ruby/rack/protection/json_csrf.rb:17:in `call'
        /usr/lib/ruby/vendor_ruby/rack/protection/base.rb:47:in `call'
        /usr/lib/ruby/vendor_ruby/rack/protection/xss_header.rb:22:in `call'
        /usr/lib/ruby/vendor_ruby/rack/logger.rb:15:in `call'
        /usr/lib/ruby/vendor_ruby/rack/head.rb:9:in `call'
        /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:21:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/showexceptions.rb:21:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1334:in `block in call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1416:in `synchronize'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1334:in `call'
        /usr/lib/ruby/vendor_ruby/rack/lint.rb:48:in `_call'
        /usr/lib/ruby/vendor_ruby/rack/lint.rb:36:in `call'
        /usr/lib/ruby/vendor_ruby/rack/showexceptions.rb:24:in `call'
        /usr/lib/ruby/vendor_ruby/rack/commonlogger.rb:20:in `call'
        /usr/lib/ruby/vendor_ruby/rack/chunked.rb:43:in `call'
        /usr/lib/ruby/vendor_ruby/rack/content_length.rb:14:in `call'
        /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:531:in `process_client'
        /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:606:in `worker_loop'
        /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:487:in `spawn_missing_workers'
        /usr/lib/ruby/vendor_ruby/unicorn/http_server.rb:137:in `start'
        /usr/bin/unicorn:121:in `<main>'
62.204.93.102 - - [08/Dec/2014 20:17:36] "POST /commit HTTP/1.1" 500 164841 0.9724
```

**Comment by chkelly** [comment]
This is now resolved. I have started updating this app now that I have time. Please ensure that you are running at least ruby-2.2 and have fetched the updates in this repo.
